window.noname_package={
    character:{
        scarlet:'红月',
        sakura:'散樱',
        imperishable:'永夜',
        immaterial:'萃梦',
        phantasmagoria:'花映',
        sb:'文花',
        baka:'笨蛋',
    },
    card:{
        standard:'标准',
        incident:'异变',
        skill:'技能',
    },
    play:{
        boss:'诸神降临',
        cardpile:'牌堆补充',
        wuxing:'五行生克',
        coin:'富甲天下',
    },
    mode:{
        old_identity:'身份',
        identity:'异变',
        versus:'对决',
        connect:'联机',
        boss:'挑战',
        chess:'战棋',
        tafang:'塔防',
        brawl:'场景',
        library:'图鉴',
    },
    background:{
        shengshi_bg:'盛世',
    },
    music:{
        music_diaochan:'貂蝉',
    },
    font:{
        xiaozhuan:'小篆',
        xinwei:'新魏',
        huangcao:'黄草',
        lishu:'隶书',
    },
    theme:{
        woodden:'木纹',
        music:'音乐',
        simple:'简约',
    }
};
