window.noname_package={
    character:{
        standard:'标准',
        scarlet:'红月',
    },
    card:{
        standard:'标准',
    },
    play:{
        boss:'诸神降临',
        cardpile:'牌堆补充',
        wuxing:'五行生克',
        coin:'富甲天下',
    },
    mode:{
        identity:'身份',
        versus:'对决',
        connect:'联机',
        boss:'挑战',
        chess:'战棋',
        brawl:'场景',
        library:'图鉴',
    },
    background:{
        shengshi_bg:'盛世',
    },
    music:{
        music_diaochan:'貂蝉',
        music_shezhan:'舌战',
        music_danji:'单骑',
    },
    font:{
        xiaozhuan:'小篆',
        xinwei:'新魏',
        huangcao:'黄草',
        lishu:'隶书',
    },
    theme:{
        woodden:'木纹',
        music:'音乐',
        simple:'简约',
    }
};
