character.pack={
    standard:'标准',
};
card.pack={
    standard:'标准',
};
play.pack={
    boss:'挑战武将',
    cardpile:'牌堆补充',
    character:'技能卡牌',
    soldier:'士兵模式',
    wuxing:'五行生克',
    weather:'天气变化',
    coin:'富甲天下',
};
mode.pack={
    identity:'身份',
    versus:'对决',
    connect:'联机',
    boss:'挑战',
    chess:'战棋',
    brawl:'场景',
};
background.pack={
    zhulian_bg:'璧合',
    zhulin_bg:'竹林',
    shengshi_bg:'盛世',
    xueji_bg:'雪霁',
    yinxiang_bg:'印象',
    huangtian_bg:'黄天',
};
music.pack={
    music_diaochan:'貂蝉',
    music_shezhan:'舌战',
    music_danji:'单骑',
};
font.pack={
    xiaozhuan:'小篆',
    xinwei:'新魏',
    huangcao:'黄草',
    lishu:'隶书',
};
theme.pack={
    woodden:'木纹',
    music:'音乐',
    simple:'简约',
}
