window.noname_update={
    version:'0.70',
    update:'0.68',
    changeLog:[
        '更新成功！',
    ],
    files:[
        //'game/game.js',
        'game/*',
        // 'game/package.js',
        // 'game/config.js',
        // 'game/source.js',
        // 'game/pressure.js',
        // 'game/asset.js',
         'card/*',
        // 'card/standard.js',
        // 'card/gwent.js',
        // 'card/gujian.js',
         'character/*',
        // 'character/hearth.js',
        // 'character/old.js',
        // 'character/gwent.js',
        // 'character/sp.js',
        // 'character/swd.js',
        // 'character/rank.js',
        // 'character/yijiang.js',
        // 'character/xianjian.js',
        'mode/*',
        // 'mode/identity.js',
        // 'mode/guozhan.js',
        // 'mode/versus.js',
        // 'mode/connect.js',
        // 'mode/chess.js',
        // 'mode/tafang.js',
        // 'mode/guozhan.js',
        // 'mode/stone.js',
        // 'theme/music/style.css',
        // 'theme/woodden/style.css',
        // 'theme/simple/style.css',
        // 'layout/default/layout.css',
        // 'layout/default/phone.css',
        // 'layout/default/menu.css',
        // 'theme/style/cardback/*',
        // 'layout/long/layout.css',
        // 'layout/long2/layout.css',
        // 'layout/mobile/layout.css',
        // 'layout/newlayout/global.css',
        // 'layout/mode/chess.css',
        // 'extension/boss/extension.js',
    ]
}
